<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_UpdateEventTimestampWithSystemTime" Id="{90d4bcb1-26f4-4eb7-bae3-1d2f76cf9b17}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_UpdateEventTimestampWithSystemTime
VAR_INPUT
	stEvent : Reference to ST_Event;
END_VAR
VAR
	fbGETSYSTEMTIME : GETSYSTEMTIME;
	
	stFileTime : T_FILETIME;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbGETSYSTEMTIME(timeLoDW => stFileTime.dwLowDateTime,
				timeHiDW => stFileTIme.dwHighDateTime);
stEvent.dtTimestamp := FILETIME_TO_DT(fileTime := stFileTime);]]></ST>
    </Implementation>
    <LineIds Name="F_UpdateEventTimestampWithSystemTime">
      <LineId Id="7" Count="0" />
      <LineId Id="18" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>