<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_XmlPersistentEventStorage" Id="{e3123194-14a3-47a7-8c04-689e285d04b2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_XmlPersistentEventStorage IMPLEMENTS I_PersistentEventStorage
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//]]></ST>
    </Implementation>
    <Method Name="StoreEvent" Id="{68fa816d-474b-490e-afc3-2cfd852098d7}">
      <Declaration><![CDATA[METHOD StoreEvent
VAR_INPUT
	stEvent	: ST_Event;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_XmlPersistentEventStorage">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_XmlPersistentEventStorage.StoreEvent">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>